# Generated by Django 4.2.4 on 2023-12-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommodel',
            name='avatart_number',
            field=models.IntegerField(default=0),
        ),
    ]
